export enum EnumCookies {
	ACCESS_TOKEN = 'TWELBI-ACCESS',
	REFRESH_TOKEN = 'TWELBI-XLSF',
	SESSION = 'TWELBI-IRON',
}

export enum EnumStorage {
	CONFIRMATION_TIMER = 'TWELBI-CONFIRMATION-TIMER',
	VERIFICATION_TIMER = 'TWELBI-VERIFICATION-TIMER',
}

export enum EnumFile {
	IMAGE = 'IMAGE',
	VIDEO = 'VIDEO',
}
